### ISSUE TITLE
FR: Avoid Frontmatter

### ISSUE THREAD

**Issue by javiavid** [travisvn/obsidian-edge-tts#1]
It would be useful if the frontmatter could be avoided, normally it is metadata without interest to listen to.

**Comment by tmilktoast** [comment]
Logged into Github just to say the same thing about the frontmatter.

Also, great plugin so far. Thanks!

**Comment by travisvn** [comment]
@javiavid @tmilktoast 

Took your guys' suggestion and added Frontmatter filtering :) 

https://github.com/travisvn/obsidian-edge-tts/releases/tag/1.0.6 

Just update the plugin as usual in the settings and you should be all set 🙂
