### ISSUE TITLE
FR: Toggle reading of links, frontmatter, etc.

### ISSUE THREAD

**Issue by bladeacer** [travisvn/obsidian-edge-tts#10]
This has been a great plugin! 
However, it would be nice to toggle whether the following note contents are read:
- frontmatter
- links
- titles
- footnotes
- etc.

Ideally, this can be done via plugin settings or hotkeys

**Comment by travisvn** [comment]
Frontmatter was targeted to be removed specifically after a comment from a user requesting it. 

I do think there's a place for reading the Title and the others on your list. 

However, I do not think this should be opened as an issue and would like to redirect you to the `Discussions` tab instead. 

Here's the direct link for creating a new Idea thread: https://github.com/travisvn/obsidian-edge-tts/discussions/new?category=ideas

**Comment by bladeacer** [comment]
Thx, I will create an idea thread there.
