### ISSUE TITLE
Replace colon (`:`) in MP3 filenames to prevent ADS issues on Windows

### ISSUE THREAD

**Issue by 7shi** [travisvn/obsidian-edge-tts#14]
When generating MP3 files, the current output path format is:

```
C:\Users\USER_NAME\Documents\Obsidian Valud/Note Narration Audio/note - Dec 03 2024 23:06.mp3
```

On Windows systems, filenames containing colons (`:`) are treated as Alternate Data Streams (ADS). This results in creating an empty file named `note - Dec 03 2024 23` instead of the intended MP3 file.

Proposed Solution:

The timestamp in filenames should be sanitized by replacing any colons with underscores or another safe character. This would transform the output format to something like `note - Dec 03 2024 23_06.mp3`, ensuring proper file creation.

**Comment by travisvn** [comment]
@7shi Thank you for bringing this up. 

Are the forward slashes an issue on Windows in addition to the colon problem? 

I'm starting work on this right now 👍

**Comment by travisvn** [comment]
@7shi 

Just uploaded the fix :) https://github.com/travisvn/obsidian-edge-tts/releases/tag/1.5.0

**Comment by 7shi** [comment]
Thank you for the quick fix that addresses the ADS issue by replacing colons (`:`) with hyphens (`-`). And thank you for unifying path separators to backslashes (`\`) for file generation - while Windows accepts forward slashes (`/`), having a consistent style is preferable. However, there's a small issue with the path separators in the auto-generated links, which I'll document in #15.

**Comment by 7shi** [comment]
I found an issue with path separators in vault paths. When paths containing backslashes (`\`) are used in the vault files, the file tree display becomes incorrect.

![image](https://github.com/user-attachments/assets/9091727a-c5c4-4519-80eb-22202b050cd2)

Although files are stored in their intended locations, this is purely a UI issue that can be resolved by restarting Obsidian.

Since Windows accepts both `/` and `\` in mixed paths, the original mixed path format like
```
C:\Users\USER_NAME\Documents\Obsidian Valud/Note Narration Audio/note - Dec 03 2024 23-06.mp3
```
should be kept instead of unifying them to `\`.
