### ISSUE TITLE
Inconsistent behavior between file and text context menus for MP3 generation and embedding

### ISSUE THREAD

**Issue by 7shi** [travisvn/obsidian-edge-tts#15]
There are two ways to generate MP3 from the context menu:

1. **File context menu** (right-click on file in file explorer)

   - Generates MP3 for the entire file content regardless of any text selection in the editor
   - Successfully embeds the MP3 link in the note when "Embed MP3 in note" is enabled

2. **Text context menu** (right-click on text in editor)

   - Generates MP3 for the selected text only (if selection exists)
   - Does not embed the MP3 link in the note, even when "Embed MP3 in note" is enabled

**Expected Behavior:**

The "Embed MP3 in note" feature should work consistently across both context menus:

- When using the text context menu, if there is a text selection, the MP3 link should be inserted immediately after the selected text
- If no text is selected, the behavior should match the file context menu (append at the end of the note)

**Technical Details:**

The issue stems from how the `filePath` is handled in the `generateMP3` method when called from different contexts. The file context menu correctly passes the file path:

```typescript
onClick(async () => {
    await this.generateMP3(undefined, undefined, file.path);
});
```

While the text context menu does not:

```typescript
onClick(async () => {
    await this.generateMP3(editor, view);
});
```

This leads to `undefined filePath` in `saveMP3File`, preventing the embed functionality from working.

**Comment by travisvn** [comment]
@7shi — I hadn't considered this - thank you for filing the issue

I just uploaded the fix! 🙂 https://github.com/travisvn/obsidian-edge-tts/releases/tag/1.5.0

**Comment by 7shi** [comment]
Thank you for the quick response and fix. The modified behavior is intuitive and matches what users would expect from the settings.

However, I noticed that the update also changed the path separators to backslashes (`\`) in the generated Obsidian links, like this:

```
![[Note Narration Audio\note - Dec 04 2024 18-23.mp3]]
```

While using backslashes for file system operations on Windows (as discussed in Issue #14) is appropriate, it would be better to use forward slashes (`/`) in the Markdown links. Forward slashes in the Markdown links work fine on Windows and provide better cross-platform compatibility.

Expected link format:
```
![[Note Narration Audio/note - Dec 04 2024 18-23.mp3]]
```

Thanks again for maintaining this helpful plugin!

**Comment by 7shi** [comment]
Regarding the statement about backslash usage in Issue #14, using mixed path formats like
```
C:\Users\USER_NAME\Documents\Obsidian Valud/Note Narration Audio/note - Dec 03 2024 23-06.mp3
```
(Windows path outside the vault, forward slashes inside) is preferred over enforcing backslashes throughout.

This naturally results in forward slashes (`/`) being used for paths within the vault, like:
```
![[Note Narration Audio/note - Dec 04 2024 18-23.mp3]]
```

**Comment by travisvn** [comment]
@7shi Can you provide a link to Obsidian plugin documents that recommend forward or backslashes one way or the other?

**Comment by 7shi** [comment]
@travisvn I found the following description.

https://github.com/obsidianmd/obsidian-developer-docs/blob/main/en/Plugins/Releasing/Plugin%20guidelines.md#use-normalizepath-to-clean-up-user-defined-paths

### Use `normalizePath()` to clean up user-defined paths

Use [[normalizePath|normalizePath()]] whenever you accept user-defined paths to files or folders in the vault, or when you construct your own paths in the plugin code.

`normalizePath()` takes a path and scrubs it to be safe for the file system and for cross-platform use. This function:

- Cleans up the use of forward and backward slashes, such as replacing 1 or more of `\` or `/` with a single `/`.
- Removes leading and trailing forward and backward slashes.
- Replaces any non-breaking spaces, `\u00A0`, with a regular space.
- Runs the path through [String.prototype.normalize](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize).

```ts
import { normalizePath } from 'obsidian';
const pathToPlugin = normalizePath('//my-folder\file');
// pathToPlugin contains "my-folder/file" not "//my-folder\"
```
