### ISSUE TITLE
Pause/continue function

### ISSUE THREAD

**Issue by micaelarealign** [travisvn/obsidian-edge-tts#16]
Let me first say this is  brilliant plugin. I used to have to open Edge and go to pastebin to use its voice function. Now that it's inside obsidian this is amazing. 

But I do sometimes have it read long notes, and want to stop, or pause, for any number of reasons. Is this already a feature I'm missing or is that something you plan on adding? Would that even be feasible? Maybe if it generated an MP3 first.. how does Edge implement the play pause/skip features?

**Comment by travisvn** [comment]
@micaelarealign This might be a better question to discuss over on our Discord: https://discord.gg/nH3x3KgnwE

**Comment by micaelarealign** [comment]
Never much been a fan of discord... it says the invite is invalid either way... just thought I would ask. I may go and try my hand at it if this isn't planned.

**Comment by travisvn** [comment]
@micaelarealign The invite link doesn't work?? That's concerning

Anyway, the answer to your original question is that you can pause and resume using the button in the status bar. By default, it should be in the bottom right corner of your Obsidian screen.
