### ISSUE TITLE
Add seconds to MP3 filenames or handle duplicate filenames

### ISSUE THREAD

**Issue by 7shi** [travisvn/obsidian-edge-tts#17]
When generating MP3 files in quick succession, filenames can collide and overwrite each other because the current timestamp format only includes hours and minutes, not seconds.

**Suggested Solutions:**

The filename format could be improved by either adding seconds to the timestamp or adding sequential numbers for duplicate filenames.

**Additional Consideration:**

After adding a comment to #15, I noticed that having different filename formats across operating systems can cause issues with Obsidian Sync or manual file copying. A standardized filename format across all OS platforms would improve sync compatibility.

**Comment by travisvn** [comment]
@7shi The exclusion of seconds from default file naming helps prevent a couple of things:

1. It keeps the user from sending too many requests to the Edge service (which is in a nebulous area of approval, as Microsoft's preferred consumption would be to pay for the Azure TTS service)
2. Keeps sight on the focus of the plugin, which is to provide general narration of notes and not serve as a utility for one specific purpose (like audio snippets for portions of a note ad-infinitum)

I think if a user has the use case of needing to differentiate, then they should be manually renaming the files to something more reflective, and I believe the exclusion of seconds from the file name suits the general populace better.

**Comment by 7shi** [comment]
@travisvn Thank you for answering. I understand your point.

I think it would be better to make it an error rather than overwriting it without warning, as this would cause confusion. I think it would also help prevent abuse.
