### ISSUE TITLE
Fails on "&"

### ISSUE THREAD

**Issue by huachuman** [travisvn/obsidian-edge-tts#18]
<s>If the note is more than a couple paragraphs or if you select more than a couple hundred words, it fails, with no error message or warning. Is this just me? Is this expected to happen? Any way around it?

Right now it seems to only read very short notes. MP3 fails the same way.</s>

**Comment by jun6lee** [comment]
Good catch.. with the ampersand! At least I can replace them for now.

**Comment by travisvn** [comment]
@huachuman @jun6lee Apologies for the delay. I'll add this to my priority list for tomorrow and get back to you with the status as soon as I have something 👍 

Thank you for bringing this to my attention

**Comment by travisvn** [comment]
@huachuman @jun6lee 

Fixed! https://github.com/travisvn/obsidian-edge-tts/releases/tag/1.6.0
