### ISSUE TITLE
Does Edge-TTS work on Android? 

### ISSUE THREAD

**Issue by lrdub** [travisvn/obsidian-edge-tts#19]
Thank you for this fantastic plugin. 

Is Edge-TTS supposed to work on Android? For me, when attempting to enable it, it will disable immediately and have an error of 'failed to load plugin "edge-tts" '

**Comment by travisvn** [comment]
@lrdub This plugin does not work on Android directly. It can, however, be used to generate narrations as mp3 files, which can be listened to on your Android device (generated using Obsidian for macOS, Windows, or Linux)

I know that isn't ideal, but it's a limitation with how the mobile environment handles plugins 😕 (i.e. the text-to-speech endpoint implementation isn't possible with `edge-tts`)

**Comment by lrdub** [comment]
Thanks, this is what I've been doing, and I thought this may be the case. You may want to update your docs to say that it doesn't work in Android. Thanks again for the very useful plugin.
