### ISSUE TITLE
Avoid simultaneous playback

### ISSUE THREAD

**Issue by javiavid** [travisvn/obsidian-edge-tts#2]
If you are playing an note and change to another, you will hear both at the same time.
It would be interesting to have a basic playback control in the obsidian taskbar.

**Comment by travisvn** [comment]
I think being able to pause an existing audio narration and also to stop narration when triggering a new TTS are important features. 

These, similar to your mention, are my next priority if I can allocate time

**Comment by javiavid** [comment]
Thanks

**Comment by travisvn** [comment]
@javiavid — I'm happy to report that both features you asked for have been implemented...! 🙂 

https://github.com/travisvn/obsidian-edge-tts/releases/tag/1.2.0 

I added support for a status bar button that starts the narration and then shows a pause button or a resume button based on playback status

And if you're listening to a narration and then go to play another one in another note (or the same note), it stops the current playback so you don't hear both at the same time 😊 

Just update per usual in the settings and you should be good to go!

**Comment by javiavid** [comment]
I have tried it and it works very well, thank you.
Although I have detected that the notes are not read from the beginning. I think it didn't happen before.

Another related idea, it would be possible for a 20-character text to appear next to the pause button followed by ellipses with the title of the note to know which note is being heard?
