### ISSUE TITLE
FR: Multiple language

### ISSUE THREAD

**Issue by javiavid** [travisvn/obsidian-edge-tts#4]
It would be interesting to have language detection or, if it is very complicated, to read the frontmatter to know what the language of the text is and to read it with the appropriate voice.

**Comment by travisvn** [comment]
Multiple languages are supported. Simply choose the voice for the intended locale from https://tts.travisvn.com

**Comment by javiavid** [comment]
The problem is that I do have articles in English and Spanish. Use the same voice (language) for all languages.

**Comment by javiavid** [comment]
It works, thanks!
