### ISSUE TITLE
Would it be possible to add a playback speed adjustment feature?

### ISSUE THREAD

**Issue by kiradzS** [travisvn/obsidian-edge-tts#5]
The original playback speed is kind of slow

**Comment by travisvn** [comment]
@kiradzS — it's your lucky day.. Went ahead and added this feature! (thought it would be much more involved than it was)

🙂 Update the plugin in Obsidian and you should be good to go

**Comment by kiradzS** [comment]
> @kiradzS — it's your lucky day.. Went ahead and added this feature! (thought it would be much more involved than it was)
> 
> 🙂 Update the plugin in Obsidian and you should be good to go

You are amazing!
